In [1]:
import pandas as pd
import requests
import numpy as np
import matplotlib.pyplot as plt
#import seaborn as sns
import requests
import os
import math as mt

In [3]:
tab=pd.read_excel('/Users/stefany/Desktop/analisis_datos/da2019-Stefany2889/datos/2010_AT02__d-1.xls')

In [4]:
tab

,"AT02d-1 Tasa de deserci√≥n total por entidad federativa, nivel o tipo educativo y sexo (2008/2009)",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Entidad federativa,Primaria,NaN,NaN,NaN,Secundaria,NaN,NaN,NaN,Media superior,NaN,NaN
2,NaN,Total,Hombres,Mujeres,NaN,Total,Hombres,Mujeres,NaN,Total,Hombres,Mujeres
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aguascalientes,0.670356,0.654576,0.686852,NaN,6.34601,7.54502,5.15008,NaN,14.4328,14.8422,14.0579
5,Baja California,2.0467,2.17462,1.9136,NaN,6.591,7.48018,5.68814,NaN,18.6029,20.1989,17.0415
6,Baja California Sur,0.625902,0.561475,0.693463,NaN,5.38966,6.30893,4.44132,NaN,17.514,19.4796,15.5715
7,Campeche,0.829797,1.03976,0.609732,NaN,7.20442,8.42626,5.9521,NaN,16.2294,17.9717,14.4859
8,Coahuila,2.36774,2.40036,2.33376,NaN,5.6247,6.98628,4.25691,NaN,17.6532,19.9886,15.2786
9,Colima,-1.29161,-0.93088,-1.67702,NaN,5.61332,6.87076,4.35334,NaN,12.7414,15.0459,10.5783
10,Chiapas,2.03812,2.10415,1.96889,NaN,6.1742,6.52299,5.79783,NaN,16.2928,16.4783,16.1022
11,Chihuahua,1.38156,1.44867,1.31091,NaN,6.4863,7.48565,5.49521,NaN,18.0201,19.8333,16.309
12,Distrito Federal,0.656469,0.73305,0.577424,NaN,7.49613,9.25634,5.69182,NaN,17.564,19.93,15.1592
13,Durango,0.671255,0.871091,0.462147,NaN,5.72198,7.21464,4.22651,NaN,19.1308,20.8998,17.4864
14,Guanajuato,0.791547,1.04695,0.52429,NaN,6.04518,7.35103,4.74182,NaN,17.4436,19.6763,15.4805
15,Guerrero,1.86984,2.08887,1.64007,NaN,9.57135,10.3764,8.76584,NaN,14.1326,15.9505,12.522
16,Hidalgo,0.17316,0.290627,0.0501383,NaN,3.98335,5.1419,2.80667,NaN,16.3297,19.3317,13.5962
17,Jalisco,0.666201,0.895765,0.426621,NaN,8.25161,10.0116,6.5006,NaN,13.8213,15.8669,12.0361
18,M√©xico,0.670943,0.763065,0.575027,NaN,5.51903,6.91831,4.08403,NaN,15.7645,18.4056,13.3827
19,Michoac√°n,0.70871,0.960791,0.445565,NaN,11.235,13.2141,9.32933,NaN,16.4334,16.9921,15.9542
20,Morelos,-0.107537,0.0818782,-0.304551,NaN,5.24465,5.98876,4.51763,NaN,18.5754,20.9601,16.4598
21,Nayarit,-0.174477,0.0188411,-0.377531,NaN,5.3047,6.09314,4.49503,NaN,13.7353,14.5574,13.01
22,Nuevo Le√≥n,0.78654,0.924636,0.642126,NaN,5.14105,5.96578,4.29904,NaN,22.4382,23.6538,21.1335
23,Oaxaca,2.73227,2.92764,2.52522,NaN,5.47931,6.46936,4.4784,NaN,17.087,18.232,16.0551
24,Puebla,1.33187,1.56374,1.08985,NaN,5.33834,6.61414,4.05779,NaN,11.565,13.3071,10.0348
25,Quer√©taro,0.260541,0.451808,0.0597942,NaN,7.2779,9.5862,4.99776,NaN,14.3019,16.9107,12.0203
26,Quintana Roo,1.67718,1.7999,1.54847,NaN,6.49788,7.43745,5.53564,NaN,22.6097,24.5659,20.6785
27,San Luis Potos√≠,0.778641,1.00165,0.545135,NaN,5.7259,6.85421,4.61615,NaN,15.5534,17.2162,14.0309
28,Sinaloa,0.106025,0.428049,-0.234391,NaN,6.403,7.86092,4.9478,NaN,14.0214,15.2781,12.8321
29,Sonora,0.54385,0.765251,0.311648,NaN,6.00174,6.82302,5.17237,NaN,14.9764,16.4577,13.5749
30,Tabasco,0.707313,0.866485,0.539633,NaN,5.79376,6.4726,5.10058,NaN,13.1778,14.3172,12.0523
31,Tamaulipas,1.17568,1.35218,0.990784,NaN,5.33406,6.43666,4.22037,NaN,11.2813,12.5843,10.0235
32,Tlaxcala,0.365323,0.42502,0.303171,NaN,5.46576,7.21997,3.68482,NaN,13.5204,16.2624,10.9656
33,Veracruz,1.02319,1.31757,0.711844,NaN,5.92157,6.72232,5.11113,NaN,13.6313,15.0586,12.3139
34,Yucat√°n,0.700345,0.792351,0.602701,NaN,7.53351,9.38755,5.59809,NaN,16.3264,18.7172,13.9216
35,Zacatecas,1.04351,1.19902,0.880626,NaN,6.78582,7.843,5.72909,NaN,15.949,18.1406,14.0035
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Nacional,1.00588,1.17331,0.830634,NaN,6.41566,7.64633,5.17086,NaN,15.873,17.733,14.1308
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Desertores,149028,88897,60131,NaN,394785,236600,158185,NaN,622830,336543,286287
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Nota: Las tasas negativas se deben a las reins...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,"Fuente: INEE, c√°lculos con base en las Estad√≠s...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Salarios en gto

In [5]:
salario=pd.read_excel('/Users/stefany/Desktop/analisis_datos/da2019-Stefany2889/datos/tabulador_pe2019.xls')

In [6]:
salario

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,"SECRETAR√çA DE FINANZAS, INVERSI√ìN Y ADMINISTRACI√ìN",Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,NaN,NaN,NaN,NaN,SUBSECRETAR√çA DE ADMINISTRACI√ìN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,DIRECCI√ìN GENERAL DE RECURSOS HUMANOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,TABULADOR POR FUNCI√ìN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,TABULADOR DE SUELDOS VIGENTE A PARTIR DEL 1o. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NIVEL,TIPO,PUESTO,SUELDO BASE,CUOTAS SEGURIDAD SOCIAL,PREVISI√ìN SOCIAL,AYUDA X SERVICIOS,APOYO FAMILIAR,GRATIFICACI√ìN QUINCENAL,SUELDO MENSUAL BRUTO,IMPTO MENSUAL,ISSEG,ISSSTE,SUELDO MENSUAL NETO,PRIMA VACACIONAL,AGUINALDO
9,22,NaN,GOBERNADOR/A DEL ESTADO,59804.3,5843.07,1913.1,25897,64294.8,75374,233126,69584.3,5082.66,760.41,157699,10 D√≠as por A√±o,45 D√≠as por A√±o
10,20,NaN,SECRETARIO/A DE ESTADO A,49025.9,5843.07,1913.1,22783,48858.8,67187.6,195612,56829.3,5082.66,760.41,132939,10 D√≠as por A√±o,45 D√≠as por A√±o
11,19,NaN,DIRECTOR/A GENERAL PARAESTATAL A,40686,5843.07,1913.1,18805,41397.7,49230.8,157876,43999.1,5082.66,760.41,108033,10 D√≠as por A√±o,45 D√≠as por A√±o
12,19,NaN,SECRETARIO/A DE ESTADO B,40686,5843.07,1913.1,18805,41397.7,49230.8,157876,43999.1,5082.66,760.41,108033,10 D√≠as por A√±o,45 D√≠as por A√±o
13,18,NaN,SECRETARIO/A DE ESTADO C,37083.7,5843.07,1913.1,16756,35924.2,42651.9,140172,37979.9,5082.66,760.41,96349.1,10 D√≠as por A√±o,45 D√≠as por A√±o
14,18,NaN,SUBSECRETARIO/A A,37083.7,5843.07,1913.1,16756,35924.2,42651.9,140172,37979.9,5082.66,760.41,96349.1,10 D√≠as por A√±o,45 D√≠as por A√±o
15,18,NaN,DIRECTOR/A GENERAL PARAESTATAL B,37083.7,5843.07,1913.1,16756,35924.2,42651.9,140172,37979.9,5082.66,760.41,96349.1,10 D√≠as por A√±o,45 D√≠as por A√±o
16,17,NaN,SUBSECRETARIO/A B,36196.2,5843.07,1913.1,15006,29739.5,35311.6,124009,32484.6,5082.66,760.41,85681.8,10 D√≠as por A√±o,45 D√≠as por A√±o
17,17,NaN,DIRECTOR/A GENERAL PARAESTATAL C,36196.2,5843.07,1913.1,15006,29739.5,35311.6,124009,32484.6,5082.66,760.41,85681.8,10 D√≠as por A√±o,45 D√≠as por A√±o
18,16,NaN,SUBSECRETARIO/A C,29462.2,5621.67,1913.1,10471,26559.2,33446.7,107474,26937.8,4861.26,760.41,74914.5,10 D√≠as por A√±o,45 D√≠as por A√±o
19,16,NaN,DIRECTOR/A GENERAL PARAESTATAL D,29462.2,5621.67,1913.1,10471,26559.2,33446.7,107474,26937.8,4861.26,760.41,74914.5,10 D√≠as por A√±o,45 D√≠as por A√±o
20,16,NaN,COORDINADOR/A GENERAL A,29462.2,5621.67,1913.1,10471,26559.2,33446.7,107474,26937.8,4861.26,760.41,74914.5,10 D√≠as por A√±o,45 D√≠as por A√±o
21,15,NaN,SUBSECRETARIO/A D,25790.6,5015.86,1913.1,8973,26293.7,29531.3,97517.5,23852.2,4255.45,760.41,68649.5,10 D√≠as por A√±o,45 D√≠as por A√±o
22,15,NaN,COORDINADOR/A GENERAL B,25790.6,5015.86,1913.1,8973,26293.7,29531.3,97517.5,23852.2,4255.45,760.41,68649.5,10 D√≠as por A√±o,45 D√≠as por A√±o
23,15,NaN,DIRECTOR/A GENERAL A,25790.6,5015.86,1913.1,8973,26293.7,29531.3,97517.5,23852.2,4255.45,760.41,68649.5,10 D√≠as por A√±o,45 D√≠as por A√±o
24,14,NaN,DIRECTOR/A DE AREA A,23736.5,4628.62,1913.1,6554,21043.7,23043,80918.8,18664.6,3916.52,712.095,57625.7,10 D√≠as por A√±o,45 D√≠as por A√±o
25,14,NaN,COORDINADOR/A GENERAL C,23736.5,4628.62,1913.1,6554,21043.7,23043,80918.8,18664.6,3916.52,712.095,57625.7,10 D√≠as por A√±o,45 D√≠as por A√±o
26,14,NaN,DIRECTOR/A GENERAL B,23736.5,4628.62,1913.1,6554,21043.7,23043,80918.8,18664.6,3916.52,712.095,57625.7,10 D√≠as por A√±o,45 D√≠as por A√±o
27,13,NaN,COORDINADOR/A DE PROGRAMAS,22680.8,4422.76,1913.1,4906,16798.8,19519.3,70240.8,15454.8,3742.33,680.424,50363.2,10 D√≠as por A√±o,45 D√≠as por A√±o
28,13,NaN,DIRECTOR/A DE AREA B,22680.8,4422.76,1913.1,4906,16798.8,19519.3,70240.8,15454.8,3742.33,680.424,50363.2,10 D√≠as por A√±o,45 D√≠as por A√±o
29,13,NaN,DIRECTOR/A GENERAL C,22680.8,4422.76,1913.1,4906,16798.8,19519.3,70240.8,15454.8,3742.33,680.424,50363.2,10 D√≠as por A√±o,45 D√≠as por A√±o
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,6,NaN,ESPECIALISTA TECNICO/A C,6999.17,1364.84,1913.1,863,5469.56,5026.42,21636.1,3036.48,1154.86,209.975,17234.8,10 D√≠as por A√±o,45 D√≠as por A√±o
59,6,NaN,ADMINISTRADOR/A COMERCIAL A,6999.17,1364.84,1913.1,863,5469.56,5026.42,21636.1,3036.48,1154.86,209.975,17234.8,10 D√≠as por A√±o,45 D√≠as por A√±o
60,5,A,POLICIA TERCERO A,5298.13,1033.14,1913.1,785,6453.27,2968,18450.6,2426.92,874.191,158.944,14990.6,10 D√≠as por A√±o,45 D√≠as por A√±o
61,5,NaN,ESPECIALISTA ADMINISTRATIVO/A B,5298.13,1033.14,1913.1,785,4653.95,2968,16651.3,2042.59,874.191,158.944,13575.6,10 D√≠as por A√±o,45 D√≠as por A√±o
62,5,NaN,ESPECIALISTA TECNICO/A D,5298.13,1033.14,1913.1,785,4653.95,2968,16651.3,2042.59,874.191,158.944,13575.6,10 D√≠as por A√±o,45 D√≠as por A√±o
63,5,NaN,JEFE/A DE UNIDAD B,5298.13,1033.14,1913.1,785,4653.95,2968,16651.3,2042.59,874.191,158.944,13575.6,10 D√≠as por A√±o,45 D√≠as por A√±o
64,5,NaN,ADMINISTRADOR/A COMERCIAL B,5298.13,1033.14,1913.1,785,4653.95,2968,16651.3,2042.59,874.191,158.944,13575.6,10 D√≠as por A√±o,45 D√≠as por A√±o
65,4,A,POLICIA,4592.88,895.612,1913.1,450,6560.09,936.54,15348.2,1793.62,757.825,137.786,12659,10 D√≠as por A√±o,45 D√≠as por A√±o
66,4,NaN,ESPECIALISTA TECNICO/A E,4564.19,890.016,1913.1,450,3599.73,936.54,12353.6,1173.96,753.091,136.926,10289.6,10 D√≠as por A√±o,45 D√≠as por A√±o
67,4,NaN,ESPECIALISTA ADMINISTRATIVO/A C,4564.19,890.016,1913.1,450,3599.73,936.54,12353.6,1173.96,753.091,136.926,10289.6,10 D√≠as por A√±o,45 D√≠as por A√±o
68,4,NaN,ESPECIALISTA DE SERVICIOS,4564.19,890.016,1913.1,450,3599.73,936.54,12353.6,1173.96,753.091,136.926,10289.6,10 D√≠as por A√±o,45 D√≠as por A√±o
69,4,NaN,ADMINISTRADOR/A COMERCIAL C,4564.19,890.016,1913.1,450,3599.73,936.54,12353.6,1173.96,753.091,136.926,10289.6,10 D√≠as por A√±o,45 D√≠as por A√±o
70,3,NaN,OPERADOR/A COMERCIAL A,4129.41,805.235,1913.1,450,3347.79,795.03,11440.6,1025.54,681.353,123.882,9609.79,10 D√≠as por A√±o,45 D√≠as por A√±o
71,3,NaN,OPERADOR/A TECNICO/A A,4129.41,805.235,1913.1,450,3347.79,795.03,11440.6,1025.54,681.353,123.882,9609.79,10 D√≠as por A√±o,45 D√≠as por A√±o
72,3,NaN,OPERADOR/A DE SERVICIOS A,4129.41,805.235,1913.1,450,3347.79,795.03,11440.6,1025.54,681.353,123.882,9609.79,10 D√≠as por A√±o,45 D√≠as por A√±o
73,3,NaN,OPERADOR/A ADMINISTRATIVO/A A,4129.41,805.235,1913.1,450,3347.79,795.03,11440.6,1025.54,681.353,123.882,9609.79,10 D√≠as por A√±o,45 D√≠as por A√±o
74,3,NaN,CADETE EN FORMACION A,4129.41,805.235,1913.1,450,3347.79,795.03,11440.6,1025.54,681.353,123.882,9609.79,10 D√≠as por A√±o,45 D√≠as por A√±o
75,2,NaN,OPERADOR/A TECNICO/A B,3732.06,727.752,1913.1,450,2825.63,135.31,9783.85,761.262,615.79,111.962,8294.84,10 D√≠as por A√±o,45 D√≠as por A√±o
76,2,NaN,OPERADOR/A COMERCIAL B,3732.06,727.752,1913.1,450,2825.63,135.31,9783.85,761.262,615.79,111.962,8294.84,10 D√≠as por A√±o,45 D√≠as por A√±o
77,2,NaN,OPERADOR/A DE SERVICIOS B,3732.06,727.752,1913.1,450,2825.63,135.31,9783.85,761.262,615.79,111.962,8294.84,10 D√≠as por A√±o,45 D√≠as por A√±o
78,2,NaN,OPERADOR/A ADMINISTRATIVO/A B,3732.06,727.752,1913.1,450,2825.63,135.31,9783.85,761.262,615.79,111.962,8294.84,10 D√≠as por A√±o,45 D√≠as por A√±o
79,2,NaN,CADETE EN FORMACION B,3732.06,727.752,1913.1,450,2825.63,135.31,9783.85,761.262,615.79,111.962,8294.84,10 D√≠as por A√±o,45 D√≠as por A√±o
80,1,NaN,OPERADOR/A COMERCIAL C,3374.28,657.984,1913.1,450,2364.75,34.39,8794.51,639.355,556.756,101.228,7497.17,10 D√≠as por A√±o,45 D√≠as por A√±o
81,1,NaN,OPERADOR/A TECNICO/A C,3374.28,657.984,1913.1,450,2364.75,34.39,8794.51,639.355,556.756,101.228,7497.17,10 D√≠as por A√±o,45 D√≠as por A√±o
82,1,NaN,OPERADOR/A DE SERVICIOS C,3374.28,657.984,1913.1,450,2364.75,34.39,8794.51,639.355,556.756,101.228,7497.17,10 D√≠as por A√±o,45 D√≠as por A√±o
83,1,NaN,OPERADOR/A ADMINISTRATIVO/A C,3374.28,657.984,1913.1,450,2364.75,34.39,8794.51,639.355,556.756,101.228,7497.17,10 D√≠as por A√±o,45 D√≠as por A√±o
84,1,A,OPERADOR/A ADMINISTRATIVO/A D,3080.4,600.678,1913.1,450,1572.33,0,7616.51,263.884,508.266,92.412,6751.95,10 D√≠as por A√±o,45 D√≠as por A√±o
85,1,A,OPERADOR/A DE SERVICIOS D,3080.4,600.678,1913.1,450,1572.33,0,7616.51,263.884,508.266,92.412,6751.95,10 D√≠as por A√±o,45 D√≠as por A√±o
86,1,A,OPERADOR/A COMERCIAL D,3080.4,600.678,1913.1,450,1572.33,0,7616.51,263.884,508.266,92.412,6751.95,10 D√≠as por A√±o,45 D√≠as por A√±o
87,1,A,OPERADOR/A TECNICO/A D,3080.4,600.678,1913.1,450,1572.33,0,7616.51,263.884,508.266,92.412,6751.95,10 D√≠as por A√±o,45 D√≠as por A√±o

Ya que se tiene categor√≠as de sueldo por

¬øQue porcentaje de su sueldo se pierde por las cuotas al issste, impuestos y inseg, respectivamente, para cada puesto?
¬øPorcentaje se da de apoyo en sus diferentes modalidades para cada uno?
Es equitativo o que definiria si hay un aumento o disminuci√≥n de estos valores

In [7]:
url1 = "https://www.ncbi.nlm.nih.gov/books/NBK532684/table/ch4.tab1/?report=objectonly"
file1 = 'Population.csv'
if not os.path.isfile(file1):
    html1 = requests.get(url1).content
    df_list1 = pd.read_html(html1, header = 1)
    df1 = df_list1[-1]
    df1.to_csv('Population.csv')
else:
    df1 = pd.read_csv(file1)
df1


#url='https://smn.cna.gob.mx/tools/RESOURCES/com_archivo_datos_resumenes/201801010000Lluv.csv'
#html_tem= requests.get(url).content
#Birth_rate = pd.read_csv(html)[5]

,"Sex, race, Hispanic origin, and year",Total resident population,Under 1 year,1‚Äì4 years,5‚Äì14 years,15‚Äì24 years,25‚Äì34 years,35‚Äì44 years,45‚Äì54 years,55‚Äì64 years,65‚Äì74 years,75‚Äì84 years,85 years and over
0,All persons,Number in thousands,Number in thousands,Number in thousands,Number in thousands,Number in thousands,Number in thousands,Number in thousands,Number in thousands,Number in thousands,Number in thousands,Number in thousands,Number in thousands
1,1950,150697,3147,13017,24319,22098,23759,21450,17343,13370,8340,3278,577
2,1960,179323,4112,16209,35465,24020,22818,24081,20485,15572,10997,4633,929
3,1970,203212,3485,13669,40746,35441,24907,23088,23220,18590,12435,6119,1511
4,1980,226546,3534,12815,34942,42487,37082,25635,22800,21703,15581,7729,2240
5,1990,248710,3946,14812,35095,37013,43161,37435,25057,21113,18045,10012,3021
6,2000,281422,3806,15370,41078,39184,39892,45149,37678,24275,18391,12361,4240
7,2010,308746,3944,16257,41026,43626,41064,41071,45007,36483,21713,13061,5493
8,2014,318857,3948,15929,41191,43980,43517,40513,43459,40078,26398,13683,6162
9,2015,321419,3978,15929,41110,43848,44137,40590,43188,40878,27551,13923,6287
10,2016,323128,3970,15957,41048,43511,44677,40470,42787,41463,28630,14234,6380
11,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1950,74833,1602,6634,12375,10918,11597,10588,8655,6697,4024,1507,237
13,1960,88331,2090,8240,18029,11906,11179,11755,10093,7537,5116,2025,362
14,1970,98912,1778,6968,20759,17551,12217,11231,11199,8793,5437,2436,542
15,1980,110053,1806,6556,17855,21419,18382,12570,11009,10152,6757,2867,682
16,1990,121239,2018,7581,17971,18915,21564,18510,12232,9955,7907,3745,841
17,2000,138054,1949,7862,21043,20079,20121,22448,18497,11645,8303,4879,1227
18,2010,151781,2014,8305,20970,22318,20632,20436,22142,17601,10097,5477,1790
19,2014,156936,2018,8138,21030,22523,21970,20159,21425,19322,12349,5893,2109
20,2015,158229,2035,8142,20980,22466,22299,20204,21299,19715,12892,6024,2174
21,2016,159079,2030,8156,20949,22293,22600,20153,21106,19999,13391,6177,2225
22,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1950,75864,1545,6383,11944,11181,12162,10863,8688,6672,4316,1771,340
24,1960,90992,2022,7969,17437,12114,11639,12326,10393,8036,5881,2609,567
25,1970,104300,1707,6701,19986,17890,12690,11857,12021,9797,6998,3683,969
26,1980,116493,1727,6259,17087,21068,18700,13065,11791,11551,8824,4862,1559
27,1990,127471,1928,7231,17124,18098,21596,18925,12824,11158,10139,6267,2180
28,2000,143368,1857,7508,20034,19105,19771,22701,19181,12629,10088,7482,3013
29,2010,156964,1930,7952,20056,21309,20432,20635,22864,18882,11617,7584,3704
...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,1990,11388,279,980,2128,2376,2310,1471,818,551,312,131,32
112,2000,18162,395,1506,3469,3564,3494,2653,1551,804,474,203,50
113,2010,25619,515,2094,4755,4648,4419,3734,2736,1535,735,352,95
114,2014,28018,517,2097,5107,4868,4666,4083,3194,1955,964,428,140
115,2015,28603,523,2099,5171,4912,4710,4179,3301,2076,1030,448,152
116,2016,29016,524,2099,5238,4932,4745,4222,3372,2166,1091,465,162
117,Hispanic or Latina female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,1980,7329,181,634,1482,1546,1249,805,615,411,257,117,30
119,1990,10966,268,939,2039,2028,2073,1448,868,632,403,209,59
120,2000,17144,376,1441,3318,3017,3016,2476,1585,907,603,303,101
121,2010,24859,497,2008,4561,4206,4016,3564,2728,1679,914,510,176
122,2014,27370,496,2021,4920,4551,4215,3910,3136,2099,1166,607,248
123,2015,27989,501,2020,4987,4617,4273,3997,3239,2214,1242,633,267
124,2016,28455,502,2021,5055,4661,4321,4027,3317,2304,1310,657,284
125,"White, not Hispanic or Latino male",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,1980,88035,1308,4772,13317,16554,14739,10284,9229,8803,5906,2519,603
127,1990,91743,1351,5181,12525,13219,15967,14481,9875,8303,6837,3275,729
128,2000,96551,1163,4761,13238,12628,12958,16088,14223,9312,6894,4225,1062
129,2010,98386,1067,4438,11817,12930,12171,12813,15606,13434,8045,4536,1528
130,2014,99042,1055,4254,11409,12700,12739,12055,14359,14252,9715,4753,1752
131,2015,99182,1064,4249,11279,12578,12849,11943,14100,14417,10085,4827,1791
132,2016,99244,1059,4251,11174,12416,12958,11833,13826,14542,10434,4931,1820
133,"White, not Hispanic or Latina female",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,1980,92872,1240,4522,12647,16185,14711,10468,9700,9935,7707,4345,1411
135,1990,96557,1280,4909,11846,12749,15872,14520,10153,9116,8674,5491,1945
136,2000,100774,1102,4517,12529,12183,12778,16089,14446,9879,8188,6429,2633
137,2010,101741,1016,4225,11219,12426,11972,12718,15839,14049,9000,6125,3150
138,2014,102007,1007,4047,10852,12083,12460,11927,14522,14938,10730,6102,3338
139,2015,102060,1014,4039,10735,11936,12551,11806,14242,15113,11124,6146,3354
140,2016,102081,1009,4039,10635,11764,12633,11696,13942,15245,11515,6240,3363

In [8]:
arch1='/Users/stefany/Desktop/analisis_datos/da2019-Stefany2889/datos/201901010000Lluv.csv'
arch1

'/Users/stefany/Desktop/analisis_datos/da2019-Stefany2889/datos/201901010000Lluv.csv'

Para la tabla de las temperaturas y presipitaciones por estado

¬øC√≥mo varia la temperarura dependiendo de la cantidad de presipitaciones que hubo en el estado?
¬øSe puede encontrar alguna relaci√≥n entre estas temperaturas y la zona geografica?
¬ø

In [9]:
lluvias_2018 = pd.read_csv(arch1,encoding='latin-1')

print(lluvias_2018.values)
print('--------------------------')
print(lluvias_2018.values[1,4])

In [10]:
print(lluvias_2018.values)
print('--------------------------')
print(lluvias_2018.values[1,4])

[[-102.309722 21.895 'AGS' 'AGSAG' 'Aguascalientes, Ags.' 6.61]
 [-102.466944 22.188610999999998 'AGS' 'ANVAG'
  'Cincuenta Aniversario, Ags.' 10.6]
 [-102.184167 21.738611 'AGS' 'BRTAG' 'San Bartolo, Ags.' 10.5]
 ...
 [-101.71583299999999 22.3475 'ZAC' 'VHGZC' 'Villa Hidalgo, Zac.' 9.7]
 [-103.3375 21.588889 'ZAC' 'VILZC' 'Jos√© Mar√≠a Morelos, Zac.' 15.2]
 [-102.576667 22.761389 'ZAC' 'ZACZC' 'Zacatecas, Zac.' 12.02]]
--------------------------
Cincuenta Aniversario, Ags.

In [11]:
lluvias_2018[4:20:2]

,LON,LAT,EDO,CLAVE_SIH,NOMBRE,ENE
4,-102.676944,21.997500,AGS,CDRAG,"La Codorniz, Ags.",16.70
6,-102.189167,21.826667,AGS,CLVAG,"Calvillo, Ags.",9.20
8,-102.296667,22.362778,AGS,CSOAG,"Cos√≠o, Ags.",7.20
10,-102.788333,21.807500,AGS,MNLAG,"Media Luna, Ags.",24.30
12,-102.001944,22.020556,AGS,NVLAG,"El Novillo, Ags.",15.50
14,-102.465000,22.189167,AGS,P50ANIV,"Presa Cincuenta Aniversario, Ags. SMN*",10.40
16,-102.291944,22.162500,AGS,PBLAG,"Pabell√≥n, Ags.",6.80
18,-102.133333,22.202778,AGS,PTOAG,"Puerto de la Concepci√≥n, Ags.",11.53

In [12]:
url2 = 'https://www.indexmundi.com/map/?v=35&l=es'
html2 = requests.get(url2).content
VIH = pd.read_html(html2)[2]

In [13]:
VIH

                  Pa√≠s  VIH/SIDA - habitantes infectados con VIH/SIDA   A√±o
0            Sud√°frica                                        7100000  2018
1              Nigeria                                        3200000  2018
2                India                                        2100000  2018
3           Mozambique                                        1800000  2018
4                Kenia                                        1600000  2018
..                 ...                                            ...   ...
190           Singapur                                              0  2018
191     Estados Unidos                                              0  2018
192  S√°hara Occidental                                              0  2018
193              Samoa                                              0  2018
194        El Vaticano                                              0  2018

[195 rows x 3 columns]